- public_src/components/app/app.component.ts
- public_src/components/toolbar/toolbar.component.html
- public_src/components/toolbar/toolbar.component.ts
- public_src/services/map.service.ts
> WIP Delete unused code

- webpack.config.js
- webpack/webpack.config.dev.js
- webpack/webpack.config.prod.js
... to have the same style everywhere and to prevent Codacy/Codebeat service warnings.
> Change apostrophes to quotes in config files

- public_src/components/app/app.component.html
- public_src/components/app/app.component.ts
- public_src/components/toolbar/toolbar.component.ts
- Add dev. blog url to header
- Change init zoom/basemap and download settings
> Various small adjustments

- public_src/services/processing.service.ts
- public_src/services/storage.service.ts
- it should be visible separately only in "master relations browser" later
> Filter "public_transport=stop_area" from "Route Browser" window

- package.json
- public_src/bootstrap.ts
- public_src/components/app/app.component.html
- public_src/components/app/app.component.ts
- public_src/components/auth/auth.component.html
- public_src/components/auth/auth.component.ts
- public_src/land.html
- public_src/land_single.html
- public_src/services/storage.service.ts
- webpack/webpack.config.dev.js
- webpack/webpack.config.prod.js
Used can log in/out with OSM account now and his name is displayed in the top right corner.
I used [osmlab/OsmAuth](https://github.com/osmlab/osm-auth) github URL in `package.json` instead of NPM version because they didn't publish a new version for a long time.
> Add authorization to OSM with OAuth

- public_src/services/map.service.ts
- public_src/services/processing.service.ts
When anything is selected in the right sidebar the map should also move to make that geometry immediately visible.
- for a route - I fit the bounds of a highlighted geometry
> Add map pan effect to selected stop/platform or fitBounds to a route.

- package.json
- public_src/bootstrap.ts
- public_src/components/app/app.component.html
- public_src/components/app/app.component.ts
- public_src/services/loading.service.ts
- public_src/services/map.service.ts
- public_src/services/overpass.service.ts
- public_src/services/processing.service.ts
- it is visible and map fades to gray after the request to get new data is made. It disappears when all data are received, processed and drawn to a map.
> Add angular-busy (loading indicator) on top of a map browser

- public_src/services/map.service.ts
Fix https://github.com/dkocich/osm-pt-ngx-leaflet/issues/56
> Fix node highlight redrawing

- public_src/services/map.service.ts
- fix https://github.com/dkocich/osm-pt-ngx-leaflet/issues/49 approximate icon recentering by absolute pixels (it don't work relatively)
- fix https://github.com/dkocich/osm-pt-ngx-leaflet/issues/50 popup had to be unbinded too before adding it again
> Various small fixes (icon centering, popup reopening)

- public_src/components/app/app.component.ts
- public_src/services/map.service.ts
- public_src/services/processing.service.ts
- app listen for map view changes and shows/hides by ID table rows in the sidebar
> Add filtering of stops/platforms in the sidebar depending on map bounds

- public_src/services/map.service.ts
- public_src/services/processing.service.ts
> Add "show related" button to the popup window to show/filter routes

- package.json
- public_src/bootstrap.ts
related to https://github.com/dkocich/osm-pt-ngx-leaflet/issues/14
> Add sentry to track online app errors

- package.json
- public_src/components/app/app.component.ts
- this should fix bug with geometry moving around while zooming in/out (see Leaflet/Leaflet/issues/4247)
> Disable animation and update leaflet map

- public_src/bootstrap.ts
- public_src/components/editor/editor.component.html
- public_src/components/editor/editor.component.less
- public_src/components/editor/editor.component.ts
- public_src/components/sidebar/tag-browser.component.html
- public_src/components/sidebar/tag-browser.component.ts
- public_src/components/toolbar/toolbar.component.html
- public_src/components/toolbar/toolbar.component.ts
- public_src/components/transporter/transporter.component.html
- public_src/components/transporter/transporter.component.ts
- public_src/services/editing.service.ts
- public_src/services/map.service.ts
- public_src/services/processing.service.ts
- public_src/services/storage.service.ts
> Add basic editing functionality to the app

- package.json
- public_src/bootstrap.ts
- public_src/components/auth/auth.component.ts
- public_src/components/transporter/transporter.component.html
- public_src/components/transporter/transporter.component.ts
- public_src/services/auth.service.ts
- public_src/services/config.service.ts
- public_src/services/overpass.service.ts
It is possible to add/remove tags of nodes/relations and upload these changes to the OSM API (it is currently set to work only on OSM dev. server).
> Enable uploading of modification to tags of node/relations

- public_src/services/auth.service.ts
- public_src/services/config.service.ts
> Fix auth - change auth URLs

- public_src/components/sidebar/stop-browser.component.html
- public_src/components/sidebar/stop-browser.component.ts
- public_src/components/sidebar/tag-browser.component.ts
- public_src/services/processing.service.ts
- public_src/styles/main.less
- webpack/webpack.config.prod.js
> Adjust stop browser view in the sidebar

- public_src/services/overpass.service.ts
- public_src/services/processing.service.ts
...there is tooltip with stop area's name on mouse hover.
> Add highlighting of downloaded stop areas (rect. around all members).

- public_src/components/sidebar/route-browser.component.html
- public_src/components/sidebar/stop-browser.component.html
- public_src/components/sidebar/tag-browser.component.html
- public_src/services/map.service.ts
related to https://github.com/dkocich/osm-pt-ngx-leaflet/issues/86
> Ui adjustment = magnifiers -> rows, del. popups, adjust font

- public_src/components/sidebar/tag-browser.component.ts
- public_src/services/editing.service.ts
> Edit existing tags (saving to history, moving between changes)

- public_src/components/app/app.component.html
- public_src/components/app/app.component.ts
- public_src/services/loading.service.ts
- public_src/services/map.service.ts
related to https://github.com/dkocich/osm-pt-ngx-leaflet/issues/52
> Fix filtering + adjust loading service

- public_src/components/toolbar/toolbar.component.html
- public_src/components/toolbar/toolbar.component.less
- public_src/components/toolbar/toolbar.component.ts
- public_src/services/processing.service.ts
- public_src/services/storage.service.ts
Counters were not refreshing when new data arrived.
> Fixup stats log

- package.json
- public_src/bootstrap.ts
- public_src/components/sidebar/route-browser.component.ts
- public_src/components/sidebar/stop-browser.component.html
- public_src/components/sidebar/stop-browser.component.ts
- public_src/services/editing.service.ts
- public_src/services/processing.service.ts
~~~WIP - reordering works only sometimes now and at some point, it stops working completely?!...~~~
> Add possibility to reorder members of a relation and redraw the highlight

- public_src/components/editor/editor.component.html
- public_src/components/editor/editor.component.ts
- public_src/components/toolbar/toolbar.component.ts
- public_src/services/editing.service.ts
- public_src/services/overpass.service.ts
- public_src/services/processing.service.ts
- public_src/services/storage.service.ts
- yarn.lock
> Create new nodes (stops, platforms)

- public_src/components/sidebar/tag-browser.component.html
- public_src/components/sidebar/tag-browser.component.ts
related to https://github.com/dkocich/osm-pt-ngx-leaflet/issues/112
> Add checkboxes btns for transport types; remove table header in tag view

- public_src/services/map.service.ts
- public_src/services/storage.service.ts
- add types; fix types filtering from a relation
> Fixup broken focus on routes (err with missing coordinates); fix types

- public_src/services/config.service.ts
- public_src/services/map.service.ts
related to https://github.com/dkocich/osm-pt-ngx-leaflet/issues/23
> Add here/mapbox satellite/hybrid layers

- public_src/components/transporter/transporter.component.html
- public_src/components/transporter/transporter.component.ts
- public_src/services/config.service.ts
- public_src/services/overpass.service.ts
related to https://github.com/dkocich/osm-pt-ngx-leaflet/issues/69 
- Allow uploading of new elements (created platforms and routes with members).
- Add button to upload screen to check changeset before upload.
> Changeset creation for new elements

- public_src/components/sidebar/relation-browser.component.html
- public_src/components/sidebar/relation-browser.component.ts
- public_src/components/sidebar/route-browser.component.html
- public_src/components/sidebar/route-browser.component.ts
- public_src/components/sidebar/stop-browser.component.html
- public_src/components/sidebar/stop-browser.component.ts
- public_src/services/editing.service.ts
- public_src/services/map.service.ts
- public_src/services/overpass.service.ts
- public_src/services/processing.service.ts
- public_src/styles/main.less
related to https://github.com/dkocich/osm-pt-ngx-leaflet/issues/130
> Highlight selection in map/sidebar

- public_src/components/app/app.component.html
- public_src/services/map.service.ts
(more info here https://developers.google.com/web/tools/lighthouse/audits/noopener)
> Add rel=noopener to external links opened in a new tab

- public_src/index.html
- public_src/manifest.json
- webpack/webpack.config.dev.js
- webpack/webpack.config.prod.js
Works fine on mobile... merging
> Add manifest.json for better mobile experience

- public_src/components/toolbar/toolbar.component.html
- public_src/components/toolbar/toolbar.component.ts
- public_src/services/processing.service.ts
related to https://github.com/dkocich/osm-pt-ngx-leaflet/issues/86
> Allow to cancel current selection and disable its highlight

- angular.json
Fix #200 
... test deployment (build was too slow locally, looked like stuck around 90% for some time)
> chore: enable sourcemaps in angular.json

- public_src/components/sidebar/tag-browser.component.html
> fix: Minor fix for viewing tags

- public_src/components/app/app.component.ts
- public_src/core/metadata.interface.ts
- public_src/core/ptWay.interface.ts
- public_src/database/dexiedb.ts
- public_src/services/db.service.ts
- public_src/services/overpass.service.ts
- public_src/services/process.service.ts
- public_src/services/storage.service.ts
- IDB integration using Dexie.js
> IDB integration

- public_src/components/beginner/beginner.component.html
- public_src/components/beginner/beginner.component.ts
- public_src/components/modal/modal.component.html
- public_src/components/modal/modal.component.less
- public_src/components/modal/modal.component.ts
- public_src/components/sidebar/validation-browser.component.html
- public_src/components/sidebar/validation-browser.component.ts
- public_src/core/errorObject.interface.ts
- public_src/services/conf.service.ts
- public_src/services/error-highlight.service.ts
- public_src/services/overpass.service.ts
- public_src/services/storage.service.ts
- public_src/store/app/actions.ts
- Error highlights related to route references
> feat: references error correction

- public_src/components/editor/editor.component.html
- public_src/components/editor/editor.component.ts
Should be able to add new platforms 
Nothing happens when the 'platform' button is clicked.
- fix of toggle edit mode
> fix: toggle edit mode

- package-lock.json
- package.json
- public_src/components/toolbar/toolbar.component.html
- public_src/components/toolbar/toolbar.component.less
- public_src/components/toolbar/toolbar.component.ts
- public_src/services/map.service.ts
Related to/Fixes issue #226 
-Added option for viewing references information along with route highlight
> Route Highlight Labels

- public_src/services/error-highlight.service.ts
Related to/Fixes issue #226 
-Now validation checks for highway tag
> Update platform way highlight

- public_src/components/editor/editor.component.ts
- Update change detection strategy to default for the editor component
> Edit Counter fix

- public_src/assets/i18n/cs.json
- public_src/assets/i18n/de.json
- public_src/assets/i18n/en.json
- public_src/assets/i18n/es.json
- public_src/assets/i18n/fr.json
- public_src/components/beginner/beginner.component.ts
- public_src/components/expert/expert.component.ts
- public_src/components/modal/modal.component.html
- public_src/components/modal/modal.component.ts
- public_src/components/sidebar/validation-browser.component.html
- public_src/components/sidebar/validation-browser.component.ts
- public_src/core/editingOptions.interface.ts
- public_src/core/errorObject.interface.ts
- public_src/services/error-highlight.service.ts
- public_src/services/overpass.service.ts
- public_src/services/storage.service.ts
Related to/Fixes issue #226 
- Highlights platforms with traditional tag highway=bus_stop but without public_transport=platform. This will help transition from PT version 1 to PT version 2.
> PTv2 suggestion highlight

- public_src/assets/i18n/cs.json
- public_src/assets/i18n/de.json
- public_src/assets/i18n/en.json
- public_src/assets/i18n/es.json
- public_src/assets/i18n/fr.json
- public_src/components/app/app.component.html
- public_src/components/app/app.component.less
- public_src/components/beginner/beginner.component.ts
- public_src/components/editor/editor.component.ts
- public_src/components/expert/expert.component.ts
- public_src/components/modal/modal.component.html
- public_src/components/modal/modal.component.ts
- public_src/components/sidebar/validation-browser.component.html
- public_src/components/sidebar/validation-browser.component.ts
- public_src/core/editingOptions.interface.ts
- public_src/core/errorObject.interface.ts
- public_src/services/edit.service.ts
- public_src/services/error-highlight.service.ts
- public_src/services/overpass.service.ts
- public_src/services/storage.service.ts
- public_src/styles/main.less
Related to/Fixes issue #226 
- Add remaining functionality to corresponding stop-platform error highlight
> Add remaining functionality to corresponding stop-platform error highlight

- public_src/components/modal/modal.component.ts
- public_src/components/route-wizard/route-wizard.component.ts
- public_src/components/settings/settings.component.ts
- public_src/components/transporter/transporter.component.html
- public_src/services/db.service.ts
- public_src/services/error-highlight.service.ts
- public_src/services/map.service.ts
- public_src/services/overpass.service.ts
- public_src/services/route-master-wizard.service.ts
- public_src/services/warn.service.ts
Related to/Fixes issue #115 
- Add multiple node data response to IDB
> Add multiple node data response to IDB
